version: "3.7"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
  app:
    image: ${NAME}:${TAG}
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#  another_app:
#    image: traefik/whoami
#    ports:
#      - "9001:80"
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - app
#      - another_app